package controller;

import koneksi.Koneksi;import model.Siswa;import java.sql.*;import java.util.*;
public class SiswaController{
 public List<Siswa> getAll() throws SQLException{List<Siswa> l=new ArrayList<>();String sql="SELECT * FROM siswa ORDER BY nama_siswa";try(PreparedStatement ps=Koneksi.getConnection().prepareStatement(sql);ResultSet r=ps.executeQuery()){while(r.next())l.add(new Siswa(r.getInt("id_siswa"),r.getString("nis"),r.getString("nama_siswa"),r.getInt("id_kelas"),r.getString("jenis_kelamin"),r.getString("alamat"),r.getTimestamp("created_at")));}return l;}
 public boolean simpan(Siswa s)throws SQLException{String sql=s.getIdSiswa()==0?"INSERT INTO siswa(nis,nama_siswa,id_kelas,jenis_kelamin,alamat) VALUES(?,?,?,?,?)":"UPDATE siswa SET nis=?,nama_siswa=?,id_kelas=?,jenis_kelamin=?,alamat=? WHERE id_siswa=?";try(PreparedStatement ps=Koneksi.getConnection().prepareStatement(sql)){ps.setString(1,s.getNis());ps.setString(2,s.getNamaSiswa());ps.setInt(3,s.getIdKelas());ps.setString(4,s.getJenisKelamin());ps.setString(5,s.getAlamat());if(s.getIdSiswa()!=0)ps.setInt(6,s.getIdSiswa());return ps.executeUpdate()>0;}}
 public boolean hapus(int id)throws SQLException{try(PreparedStatement ps=Koneksi.getConnection().prepareStatement("DELETE FROM siswa WHERE id_siswa=?")){ps.setInt(1,id);return ps.executeUpdate()>0;}}
 public List<Object[]> cari(String key)throws SQLException{List<Object[]>l=new ArrayList<>();String sql="SELECT s.id_siswa,s.nis,s.nama_siswa,k.nama_kelas,s.jenis_kelamin,s.alamat FROM siswa s LEFT JOIN kelas k ON k.id_kelas=s.id_kelas WHERE s.nis LIKE ? OR s.nama_siswa LIKE ? ORDER BY s.nama_siswa";try(PreparedStatement ps=Koneksi.getConnection().prepareStatement(sql)){ps.setString(1,"%"+key+"%");ps.setString(2,"%"+key+"%");try(ResultSet r=ps.executeQuery()){while(r.next())l.add(new Object[]{r.getInt(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6)});}}return l;}
}
