package form;

import controller.PemasukanController;
import java.awt.*;
import java.time.LocalDate;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Pemasukan;
import util.UIUtils;
import util.UIUtils.Option;

public class PemasukanFrame extends JPanel {
  private final PemasukanController controller=new PemasukanController();
  private final DefaultTableModel model=new DefaultTableModel(new Object[]{"ID","Tanggal","Kategori Pemasukan","Nominal","Keterangan","ID Kategori"},0){public boolean isCellEditable(int r,int c){return false;}};
  private final JTable table=new JTable(model);
  public PemasukanFrame(){setLayout(new BorderLayout()); add(build(),BorderLayout.CENTER); loadData();}
  private JPanel build(){JPanel page=UIUtils.page("Pemasukan"); JTextField search=UIUtils.textField(18); JButton add=UIUtils.button("+ Tambah Data",UIUtils.GREEN), edit=UIUtils.button("Edit",UIUtils.ORANGE), del=UIUtils.button("Hapus",UIUtils.RED), ref=UIUtils.button("Refresh",UIUtils.BLUE), cetak=UIUtils.button("Cetak",Color.GRAY); add.addActionListener(e->dialog(null)); edit.addActionListener(e->edit()); del.addActionListener(e->delete()); ref.addActionListener(e->loadData()); cetak.addActionListener(e->UIUtils.exportTableToPdf(this,table,"Laporan Pemasukan", "Total: "+UIUtils.rupiah(total()))); TableRowSorter<DefaultTableModel> sorter=new TableRowSorter<>(model); table.setRowSorter(sorter); UIUtils.bindSearch(search,sorter); table.removeColumn(table.getColumnModel().getColumn(5)); JPanel center=new JPanel(new BorderLayout(0,14)); center.setOpaque(false); center.add(UIUtils.toolbar(search,add,edit,del,ref,cetak),BorderLayout.NORTH); center.add(UIUtils.tableScroll(table),BorderLayout.CENTER); page.add(center,BorderLayout.CENTER); return page;}
  private void loadData(){try{model.setRowCount(0); for(Pemasukan p:controller.getAll()) model.addRow(new Object[]{p.getIdPemasukan(),p.getTanggal(),p.getKategori(),UIUtils.rupiah(p.getNominal()),p.getKeterangan(),p.getIdKategoriPemasukan()});}catch(Exception e){error(e);}}
  private double total(){try{return controller.total();}catch(Exception e){return 0;}} private int selected(){int v=table.getSelectedRow(); if(v<0) JOptionPane.showMessageDialog(this,"Pilih data terlebih dahulu"); return v<0?-1:table.convertRowIndexToModel(v);}
  private void edit(){int r=selected(); if(r>=0) dialog(new Pemasukan((int)model.getValueAt(r,0),LocalDate.parse(String.valueOf(model.getValueAt(r,1))),(int)model.getValueAt(r,5),String.valueOf(model.getValueAt(r,2)),parseMoney(String.valueOf(model.getValueAt(r,3))),String.valueOf(model.getValueAt(r,4))));}
  private void delete(){int r=selected(); if(r>=0 && JOptionPane.showConfirmDialog(this,"Hapus pemasukan?","Konfirmasi",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) try{controller.delete((int)model.getValueAt(r,0)); loadData();}catch(Exception e){error(e);}}
  private void dialog(Pemasukan data){JDialog d=new JDialog(SwingUtilities.getWindowAncestor(this),data==null?"Tambah Pemasukan":"Edit Pemasukan",Dialog.ModalityType.APPLICATION_MODAL); JPanel p=UIUtils.card(); p.setLayout(new GridBagLayout()); GridBagConstraints g=new GridBagConstraints(); g.insets=new Insets(8,8,8,8); g.fill=GridBagConstraints.HORIZONTAL; JTextField tanggal=UIUtils.textField(20), nominal=UIUtils.textField(20); JComboBox<Option> kat=new JComboBox<>(); JTextArea ket=new JTextArea(4,20); ket.setFont(UIUtils.FONT); try{for(Option o:controller.kategoriOptions()) kat.addItem(o);}catch(Exception e){error(e);} tanggal.setText(LocalDate.now().toString()); if(data!=null){tanggal.setText(data.getTanggal().toString()); nominal.setText(String.valueOf(data.getNominal())); select(kat,data.getIdKategoriPemasukan()); ket.setText(data.getKeterangan());} addRow(p,g,0,"Tanggal (yyyy-mm-dd)",tanggal); addRow(p,g,1,"Kategori Pemasukan",kat); addRow(p,g,2,"Nominal",nominal); addRow(p,g,3,"Keterangan",new JScrollPane(ket)); JButton save=UIUtils.button("Simpan",UIUtils.GREEN); g.gridx=0;g.gridy=4;g.gridwidth=2;p.add(save,g); save.addActionListener(e->{try{Option o=(Option)kat.getSelectedItem(); Pemasukan pm=new Pemasukan(data==null?0:data.getIdPemasukan(),LocalDate.parse(tanggal.getText().trim()),o==null?0:o.getId(),null,Double.parseDouble(nominal.getText().trim()),ket.getText().trim()); if(data==null)controller.insert(pm); else controller.update(pm); d.dispose(); loadData();}catch(Exception ex){error(ex);}}); d.add(p); d.pack(); d.setLocationRelativeTo(this); d.setVisible(true);}
  private double parseMoney(String s){return Double.parseDouble(s.replaceAll("[^0-9,]","").replace(",","."));} private void select(JComboBox<Option> cb,int id){for(int i=0;i<cb.getItemCount();i++) if(cb.getItemAt(i).getId()==id) cb.setSelectedIndex(i);} private void addRow(JPanel p,GridBagConstraints g,int y,String l,JComponent c){g.gridy=y;g.gridx=0;g.gridwidth=1;p.add(UIUtils.formLabel(l),g);g.gridx=1;p.add(c,g);} private void error(Exception e){JOptionPane.showMessageDialog(this,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);} }
